### ISSUE TITLE
lz4.overpass-api.de was decomissioned

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/overpass-doc#16]
https://dev.overpass-api.de/overpass-doc/en/preface/commons.html

> There are currently two independent public instances, [z.overpass-api.de](https://z.overpass-api.de/api/status) and [lz4.overpass-api.de](https://lz4.overpass-api.de/api/status). We start with the explanation of and with the help of the status request.

**Comment by drolbr** [comment]
Solved by a087cc6f9df3f6aa9714d18ba8dd4cde8e2a8a46

**Comment by matkoniecz** [comment]
This one rather by https://github.com/drolbr/overpass-doc/commit/f21d592916fe331eb3a51c65c00b668f68cdc4dd
