### ISSUE TITLE
Consider adding https://dev.overpass-api.de/overpass-doc/ link in repo metadata

### ISSUE THREAD

**Issue by matkoniecz** [drolbr/overpass-doc#3]
It would clarify/confirm that this is repo of https://github.com/drolbr/overpass-doc page and allow to see it in a form easily readable by humans

**Comment by drolbr** [comment]
Where do I find the "repo metadata"?

**Comment by mmd-osm** [comment]
I think @matkoniecz proposes to have a project description added:

![grafik](https://user-images.githubusercontent.com/5842757/64609905-47a17c80-d3ce-11e9-9e66-735bee2ce4b6.png)

**Comment by matkoniecz** [comment]
Yes, exactly. Change is trivial, but it is not part of the repository so PR is impossible.

**Comment by drolbr** [comment]
Done.
