### ISSUE TITLE
French Version

### ISSUE THREAD

**Issue by Bibi56** [drolbr/overpass-doc#5]
I was checking the French making some updates (will create a PR later).
But what is the correct source? German or English?
I think German is the origin but French was translated apparently from English.
Maybe adding a comment `<!--- source: ...., version: ... --> ` the source being a language code in the translated document and in the source `<!---original, version: ... --> `
Version is not strictly needed but easier than searching in the history tree what may have changed but it works only if people do it properly.

**Comment by drolbr** [comment]
Feel free to use any of the two as a source.

I write the documentation in German, but translate it to English myself. Both versions should have the same content. Please notify my if there are diversions.

For the version tracking, I hope that the follwing helper script solves the problem:

    helper_scripts/blame_recursively.sh $LANG/index.md

The script lists all sections of all documents referred from ``$LANG/index.md`` and shows for each section the date of the latest change. Comparing two languages side-by-side should help to spot the outdated sections. The reason for this approach that we avoid to put the burden of manual version tracking on the translator.
