### ISSUE TITLE
Build script 

### ISSUE THREAD

**Issue by JVillafruela** [drolbr/overpass-doc#6]
I'd like to improve the french translation and I wonder how to build the html files. I've peered at the sh files in the "helper scripts" project and I'm puzzled by the output in html format. 

Could you provide build instructions ?

**Comment by drolbr** [comment]
Yes. I suggest to call `helper_script/convert_recursively.sh`. The syntax is:

    helper_script/convert_recursively.sh $INDEX_MD $TARGET_DIR

where `$INDEX_MD` should point to the file `index.md` including the directory path and `$TARGET_DIR` should point to the directory where the files shall be written to. For example, I call for the French version from the base directory

    helper_scripts/convert_recursively.sh fr/index.md /var/www/overpass-doc/

Another notable script is `helper_script/blame_recursively.sh`. It prints for each subsection of each file the last change date. It needs only the position of the `index.md`. I usually use

    helper_scripts/blame_recursively.sh fr/index.md >fr.log
    helper_scripts/blame_recursively.sh de/index.md >de.log
    diff -y de.log fr.log

to get an oversight whether a section in the translation has not been updated after the source section has been changed.
